### ISSUE TITLE
Completely Broken Usability and Forced Page Reloads in "Editor | Mermaid Chart"

### ISSUE THREAD

**Issue by vec2vec2** [Mermaid-Chart/issue-tracker#161]
**Describe the bug**  
The "Editor | Mermaid Chart" has multiple severe usability issues that make it almost impossible to work efficiently.  
Frequent interruptions, broken essential functions, and forced page reloads are seriously impacting the user experience.

**To Reproduce**  
1. Open the Editor in Microsoft Edge.
2. Try to add a template — it does not work.
3. Open the Editor in Google Chrome.
4. Try to adjust node parameters — it is impossible.
5. Attempt to zoom using the mouse wheel — zooming is not centered on the cursor.
6. Work for a few seconds — notice that every 10–20 seconds or 1 seconds, a "Syncing your diagram changes." popup disrupts input.
7. Wait about 1 minute — the entire page refreshes automatically.

**Expected behavior**  
- Templates should be addable on Edge.  
- Node parameters should be adjustable on Chrome.  
- Zooming should be centered on the mouse pointer.  
- There should be no intrusive sync popups during editing.  
- The page should never forcibly refresh.

**Screenshots**  
![Image](https://github.com/user-attachments/assets/400aa911-ae85-4bbb-9573-7979e865f2cb)
![Watch Video](https://github.com/user-attachments/assets/fcec1d89-629b-465b-8fff-f7137134b64c)

**Desktop (please complete the following information):**  
- OS: Windows 10  
- Browser: Microsoft Edge (latest), Google Chrome (latest)  
- Version: Edge 124.0.x / Chrome 124.0.x  

**Smartphone (please complete the following information):**  
(Not applicable)

**Additional context**  
The current implementation feels like it was never properly user-tested.  
Frequent interruptions and forced reloads make the tool completely unusable for serious work.  
Please prioritize fixing basic usability before adding any new features.

**Comment by vec2vec2** [comment]
I genuinely wonder if anyone on your team has actually used your own product before releasing it to the public.

The current experience is beyond frustrating — it borders on absurd:

Adding templates doesn't even work on Microsoft Edge. Apparently, basic functionality was optional during development?

Node parameter adjustment is broken on Google Chrome — ironic, considering Chrome is the world's most used browser.

Mouse wheel zooming completely ignores standard behavior: instead of zooming toward the cursor like every normal application, it blindly zooms the entire canvas up and down, making precise editing an absolute nightmare.

Every 10–20 seconds, an intrusive "Syncing your diagram changes." popup appears — not once, but relentlessly, interrupting anything I'm doing. It's almost as if you deliberately designed it to break concentration.

To top it all off, about once every minute, the webpage force-refreshes itself. I can only assume this is some groundbreaking new method of user torture.

Frankly, this is one of the worst-designed, least user-friendly web editors I've ever used — and that's saying something.

I sincerely hope you start taking basic usability and quality control seriously. Otherwise, I can't imagine anyone willingly using this platform for serious work.

**Comment by vec2vec2** [comment]
I can't believe how disgustingly bad this is.
I spent so much time migrating my entire mind map into this editor, only to be greeted with constant sync popups, forced reloads, broken zooming, and a completely unusable interface.
It feels like a joke — but it's not funny at all.
This is by far one of the worst, most frustrating user experiences I've ever had.
Whoever signed off on releasing this clearly never cared about users at all.

**Comment by vec2vec2** [comment]
"You’ve managed to turn what should have been a simple editor into a complete nightmare."

**Comment by vec2vec2** [comment]
If I could rate this experience, it would be a solid -120 out of 100.
Migrating my mind map here was probably the worst mistake I've made this month.

**Comment by vec2vec2** [comment]
![Image](https://github.com/user-attachments/assets/400aa911-ae85-4bbb-9573-7979e865f2cb)
It's not just every 10 seconds — it's a chaotic mess!
The "Syncing your diagram changes" popup shows up whenever it feels like, completely breaking my workflow and concentration.
No warning, no control, just pure frustration thrown at my face every few seconds.

**Comment by vec2vec2** [comment]
If you're going to force broken features on users, at least have the decency to give us an option to turn them off.
Add a simple "Auto Save / Auto Syncing" toggle button so users can disable this awful feature and actually get work done.

**Comment by vec2vec2** [comment]
https://github.com/user-attachments/assets/fcec1d89-629b-465b-8fff-f7137134b64c

**Comment by huynhicode** [comment]
Hi @vec2vec2 thanks for your feedback, is is greatly appreciated. Our team is looking into the issues that you have raised and are actively looking at addressing them. Stay tuned for updates.

**Comment by claang** [comment]
Hi @vec2vec2,  We did an update last night and the issue should be resolved. And, once again thanks for your feedback!

**Comment by GemLordNY** [comment]
> Hi [@vec2vec2](https://github.com/vec2vec2), We did an update last night and the issue should be resolved. And, once again thanks for your feedback!

Hi Claang,

Whatever you've done has not fixed the issue for me on Chrome 136.0.7103.49 on the latest Mac OS. Reloading every 40 seconds to 4 minutes makes editing in the whiteboard pretty painful. I don't get the syncing screen just a reload that zooms me out from where I am working.

**Comment by claang** [comment]
Hi @GemLordNY,

Would it be possible get the diagram code for the diagram your editing?
